#!/usr/bin/env bash

set -e

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
REPO_DIR="$SCRIPT_DIR/.."

if [ -z "$(git -C "$REPO_DIR" status --porcelain)" ]; then
  CACHE_PATH="$REPO_DIR/.cache"
  mkdir -p "$CACHE_PATH"
  STAX_PATH="$CACHE_PATH/$(git -C "$REPO_DIR" rev-parse HEAD)"
  if [ ! -f "$STAX_PATH" ]; then
    dart compile exe "$REPO_DIR/cli/bin/cli.dart" -o "$STAX_PATH" -Dversion="$(cat "$REPO_DIR/VERSION")" > /dev/null
  fi
  "$STAX_PATH" "$@"
else
  "$SCRIPT_DIR/staxlive" "$@"
fi
