#!/usr/bin/env bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
REPO_DIR="$SCRIPT_DIR/.."

if [ -z "$(git status --porcelain)" ]; then
  PATH="$HOME/.stax/staxdevcache/$(git rev-parse HEAD)"
  if [ ! -f "$PATH" ]; then
    dart compile exe "$REPO_DIR/cli/bin/cli.dart" -o "$PATH" -Dversion="$(cat "$REPO_DIR/VERSION")"
  fi
  $PATH "$@"
else
  "$SCRIPT_DIR/staxlive" "$@"
fi
