#!/usr/bin/env bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
  "$SCRIPT_DIR/bin/linux-x64/stax" "$@"
elif [[ $(uname -m) == 'arm64' ]]; then
  "$SCRIPT_DIR/bin/macos-arm64/stax" "$@"
else
  "$SCRIPT_DIR/bin/macos-x64/stax" "$@"
fi
