#!/usr/bin/env bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
(
  cd "$SCRIPT_DIR/.." &&
    git checkout main &&
    git pull &&
    dart compile exe "$SCRIPT_DIR/../cli/bin/cli.dart" --output="$SCRIPT_DIR/../bin/stax-mac" &&
    git add bin &&
    git commit -m "new release" &&
    git push
)
