name: stax
description: stax command line tool for git
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.3

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  cli_util: ^0.4.2
  collection: ^1.19.1
  http: ^1.6.0
  characters: ^1.4.1

dev_dependencies:
  lints: ^6.1.0
  test: ^1.29.0
  test_api: ^0.7.9
  meta: ^1.18.1
