name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [ "main" ]
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install dependencies
        run: dart pub get
        working-directory: cli
      - name: Build & Upload
        run:  |
          dart compile exe bin/cli.dart
          chmod +x bin/*.exe
          export TARGET_GZ=${{ matrix.os }}_${{ github.event.release.tag_name }}.tar.gz
          tar -czvf $TARGET_GZ bin/*.exe
          gh release upload ${{ github.event.release.tag_name }} $TARGET_GZ
        working-directory: cli
