name: c2w-wasm.yml
on:
  workflow_dispatch:

jobs:
  c2w:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install container2wasm
        run: |
          VERSION="v0.8.3"
          wget https://github.com/container2wasm/container2wasm/releases/download/$VERSION/container2wasm-$VERSION-linux-amd64.tar.gz
          tar -xvf container2wasm-$VERSION-linux-amd64.tar.gz
          sudo mv c2w /usr/local/bin/
      - run: mkdir -p ./guides/web/containers
      - run: .github/scripts/build_guide_docker_to_wasm amend
      - run: .github/scripts/build_guide_docker_to_wasm commit
      - run: .github/scripts/build_guide_docker_to_wasm delete-stale
      - run: .github/scripts/build_guide_docker_to_wasm doctor
      - run: .github/scripts/build_guide_docker_to_wasm get
      - run: .github/scripts/build_guide_docker_to_wasm log
      - run: .github/scripts/build_guide_docker_to_wasm move
      - run: .github/scripts/build_guide_docker_to_wasm pull
      - run: .github/scripts/build_guide_docker_to_wasm rebase
      - run: .github/scripts/build_guide_docker_to_wasm settings
      
      - uses: actions/upload-artifact@v4
        with:
          name: guides-web
          path: guides/web
          retention-days: 7
      - uses: google-github-actions/auth@v2
        with:
          service_account: brainfucksheetsgithubdeploy@youtube-355604.iam.gserviceaccount.com
          workload_identity_provider: projects/1074574117695/locations/global/workloadIdentityPools/brainfucksheet/providers/brainfucksheets
      - uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: 'guides/web'
          destination: 'staxforgit.com'
          parent: false
