name: cli-dart-test.yml
on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  cli-dart-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, macos-13, windows-latest ]

    steps:
      - uses: actions/checkout@v4
      - uses: TarasMazepa/github-action-cat@master
        id: get-dart-version
        with:
          path: DART_SDK_VERSION
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ steps.get-dart-version.outputs.text }}
      - run: dart pub get
        working-directory: cli
      - run: dart format . -o none --set-exit-if-changed
        id: format-check
        working-directory: cli
        continue-on-error: true
      - uses: peter-evans/repository-dispatch@v3
        if: steps.format-check.outcome == 'failure'
        with:
          token: ${{ secrets.PAT }}
          repository: TarasMazepa/stax
          event-type: format-dart-code
          client-payload: '{"ref": "${{ github.head_ref }}"}'
      - run: dart format . -o none --set-exit-if-changed
        if: steps.format-check.outcome == 'failure'
        working-directory: cli
      - run: dart analyze
        working-directory: cli
      - run: |
          git config --global user.name 'stax'
          git config --global user.email 'stax@staxforgit.com'
      - run: dart test
        working-directory: cli
      - run: dart compile exe bin/cli.dart
        working-directory: cli
      - run: dart compile exe bin/stax_daemon.dart
        working-directory: cli
