name: cli-update-dependencies.yml
on:
  workflow_dispatch:
  schedule:
    - cron: "25 12 * * *"

jobs:
  cli-update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: TarasMazepa/github-action-cat@main
        id: get-dart-version
        with:
          path: DART_SDK_VERSION
      - name: Cache Dart SDK
        uses: actions/cache@v4
        with:
          path: ${{ runner.tool_cache }}/dart
          key: ${{ runner.os }}-dart-${{ steps.get-dart-version.outputs.text }}
          restore-keys: |
            ${{ runner.os }}-dart-
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ steps.get-dart-version.outputs.text }}
      - name: Cache Pub dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache/hosted
            ~/.pub-cache/git
            ~/AppData/Local/Pub/Cache/hosted
            ~/AppData/Local/Pub/Cache/git
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-
      - run: dart pub upgrade --major-versions
        working-directory: cli
      - run: dart pub get
        working-directory: cli
      - run: |
          git config --global user.name 'stax'
          git config --global user.email 'stax@staxforgit.com'
      - run: dart test
        working-directory: cli
      - run: dart analyze
        working-directory: cli
      - run: dart compile exe bin/cli.dart
        working-directory: cli
      - run: dart compile exe bin/stax_daemon.dart
        working-directory: cli
      - run: |
          if ! git diff --quiet; then
            branch_name=cli-update-dependencies-$(date -u +"%Y-%m-%dT%H-%M-%S")
            git checkout -b $branch_name
            git commit -a -m "Cli update dependencies"
            git push --set-upstream origin $branch_name
            gh pr merge $(gh pr create -B main -f) --auto --squash
          fi
        env:
          GH_TOKEN: ${{ secrets.PAT }}
