name: guides-build.yml
on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  guides-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - working-directory: guides
        run: |
          for file in *.dockerfile; do
            docker buildx build --platform linux/amd64,linux/arm64 -f "$file" -t "${file%.dockerfile}-guide:$(cat ../VERSION)" .
          done
