name: guides-base-push.yml
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      guides/base.dockerfile

jobs:
  guides-base-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - run: docker login -u taras0mazepa -p ${{ secrets.DOCKER_PAT }}
      - id: get-version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t taras0mazepa/stax-guide-base:${{ steps.get-version.outputs.version }} \
            --push \
            -f "guides/base.dockerfile" \
            .
