name: release-distribution-trigger.yml
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["release-binary.yml"]
    types:
      - completed

jobs:
  release-distribution-trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: get-version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/TarasMazepa/homebrew-stax/actions/workflows/update.yml/dispatches \
            -f "ref=main" -f "inputs[tag]=${{ steps.get-version.outputs.version }}"
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.HOMEBREW_STAX_DISPATCH }}
      - run: |
          sed -i "s+<version>.*</version>+<version>$TAG</version>+" ./chocolatey/stax/stax.nuspec
          git config --global user.name 'stax'
          git config --global user.email 'stax@staxforgit.com'
          branch_name=chocolatey-update-stax-to-$TAG-$(date -u +"%Y-%m-%dT%H-%M-%S")
          git checkout -b $branch_name
          git commit -a -m "Chocolatey update stax to $TAG"
          git push --set-upstream origin $branch_name
          gh pr merge $(gh pr create -B main -f) --auto --squash
        env:
          TAG: ${{ steps.get-version.outputs.version }}
          GH_TOKEN: ${{ secrets.PAT }}
