name: release-creation.yml
on:
  push:
    branches: [ "main" ]
    paths:
      VERSION

jobs:
  release-creation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: get-version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.get-version.outputs.version }}',
              sha: context.sha
            })
      - run: gh release create $TAG
        env:
          GH_TOKEN: ${{ secrets.PAT }}
          TAG: ${{ steps.get-version.outputs.version }}
