on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
  release:
    types:
      - created

env:
  REF: ${{ github.event.release.tag_name ?? inputs.tag }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    permissions: write-all
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, macos-13, windows-latest ]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: $REF
      - uses: pCYSl5EDgo/cat@master
        id: get-dart-version
        with:
          path: DART_SDK_VERSION
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ steps.get-dart-version.outputs.text }}
      - run: dart pub get
        working-directory: cli
      - run: dart compile exe bin/cli.dart -o bin/stax
        working-directory: cli
      - run: tar -czvf ${{ matrix.os }}_.tar.gz bin/stax
        working-directory: cli
      - run: gh release upload $REF ${{ matrix.os }}_.tar.gz
        working-directory: cli
