name: update-flutter-and-dart-versions.yml
on:
  workflow_dispatch:
  schedule:
    - cron: "17 6 * * *"

jobs:
  update-flutter-and-dart-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - run: |
          brew install leoafarias/fvm/fvm
          fvm api releases -c --limit=1 --filter-channel stable
          recent_version="$(fvm api releases -c --limit=1 --filter-channel stable | jq -r '.versions[0]')"
          new_flutter_version="$(echo $recent_version | jq -r '.version')"
          new_dart_version="$(echo $recent_version | jq -r '.dart_sdk_version')"
          echo $new_flutter_version > FLUTTER_VERSION
          echo $new_dart_version > DART_SDK_VERSION
          if ! git diff --quiet; then
            branch_name=update-flutter-to-$new_flutter_version-and-dart-to-$new_dart_version-$(date -u +"%Y-%m-%dT%H-%M-%S")
            git config --global user.name 'stax'
            git config --global user.email 'stax@staxforgit.com'
            git checkout -b $branch_name
            git commit -a -m "Update flutter to $new_flutter_version and dart to $new_dart_version"
            git push --set-upstream origin $branch_name
            gh pr merge $(gh pr create -B main -f) --auto --squash
          fi
        env:
          GH_TOKEN: ${{ secrets.PAT }}
