on:
  push:
    branches: [ "main" ]
    paths:
      VERSION

jobs:
  version-trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: getversion
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/TarasMazepa/homebrew-stax/actions/workflows/update.yml/dispatches \
            -f "ref=main" -f "inputs[tag]=${{ steps.getversion.outputs.version }}"
        env:
          GH_TOKEN: ${{ secrets.HOMEBREW_STAX_DISPATCH }}
      - run: |
          sed -i "s+<version>.*</version>+<version>$TAG</version>+" ./chocolatey/stax/stax.nuspec
          sed -i "s+$tag = '.*'+$tag = '$TAG'+" ./chocolatey/stax/tools/chocolateyinstall.ps1
          checksum=$(curl -sL https://github.com/TarasMazepa/stax/archive/$TAG.zip | sha256sum | sed 's/  -//')
          sed -i "s+-Checksum .*+-Checksum $checksum \`+" ./chocolatey/stax/tools/chocolateyinstall.ps1
          git config --global user.name 'stax'
          git config --global user.email 'stax@staxforgit.com'
          git checkout -b chocolatey-update-stax-to-$TAG
          git commit -a -m "Chocolatey update stax to $TAG"
          git push --set-upstream origin chocolatey-update-stax-to-$TAG
        env:
          TAG: ${{ steps.getversion.outputs.version }}
          GH_TOKEN: ${{ secrets.PAT }}
      - run: |
          gh pr merge $(gh pr create -B main -f) --auto --squash
        env:
          GH_TOKEN: ${{ secrets.PAT }}
