name: version-to-cli-sync.yml
on:
  push:
    branches: [ "main" ]
    paths:
      VERSION

jobs:
  version-to-cli-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: get-version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - run: |
          sed -i "s+defaultValue: '.*',+defaultValue: '${{ steps.get-version.outputs.version }}',+" ./cli/lib/command/internal_command_version.dart
          git config --global user.name 'stax'
          git config --global user.email 'stax@staxforgit.com'
          branch_name=update-cli/lib/command/internal_command_version.dart-to-have-${{ steps.get-version.outputs.version }}-as-a-default-version-$RANDOM
          git checkout -b $branch_name
          git commit -a -m "Update cli/lib/command/internal_command_version.dart to have ${{ steps.get-version.outputs.version }} as a default version"
          git push --set-upstream origin $branch_name
          gh pr merge $(gh pr create -B main -f) --auto --squash
        env:
          GH_TOKEN: ${{ secrets.PAT }}
